version: "3.9"
services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: satish
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U satish -d user_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pgdata:
