name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: stsdev46
          password: dckr_pat_4yrS-_70MHeGwucZ1tV9DfQ5DQY

      - name: Build Docker image
        run: docker build -t stsdev46/user_service:latest .

      - name: Push Docker image
        run: docker push stsdev46/user_service:latest
